{ ... }:
{
  # SSH host private keys used by agenix to decrypt secrets at activation time.
  # The ed25519 key is preferred; rsa is kept as fallback.
  # These are the same keys generated by openssh on first boot.
  age.identityPaths = [
    "/etc/ssh/ssh_host_ed25519_key"
    "/etc/ssh/ssh_host_rsa_key"
  ];

  # SSH key for GitHub
  age.secrets."ssh_key_github" = {
    file = ./secrets/ssh_key_github.age;
    owner = "bittermang";
    group = "users";
    mode = "0600";
  };

  # SSH key for hobbs server
  age.secrets."ssh_key_hobbs" = {
    file = ./secrets/ssh_key_hobbs.age;
    owner = "bittermang";
    group = "users";
    mode = "0600";
  };

  # SSH key for HALLpass.space
  age.secrets."ssh_key_hallpass" = {
    file = ./secrets/ssh_key_hallpass.age;
    owner = "bittermang";
    group = "users";
    mode = "0600";
  };

  # GitHub personal access token
  age.secrets."github_token" = {
    file = ./secrets/github_token.age;
    owner = "bittermang";
    group = "users";
    mode = "0600";
  };

  # GPG private key for commit signing
  age.secrets."gpg_key" = {
    file = ./secrets/gpg_key.age;
    owner = "bittermang";
    group = "users";
    mode = "0600";
  };

  # WireGuard client private key (2600AD)
  age.secrets."wg-2600ad-privatekey" = {
    file = ./secrets/wg-2600ad-privatekey.age;
    owner = "root";
    group = "root";
    mode = "0400";
  };

  # WireGuard preshared key (2600AD <-> HALLpass.space)
  age.secrets."wg-hallspace-psk" = {
    file = ./secrets/wg-hallspace-psk.age;
    owner = "root";
    group = "root";
    mode = "0400";
  };

  # Syncthing GUI password (plaintext file; Syncthing hashes internally)
  age.secrets."syncthing-gui-pass" = {
    file = ./secrets/syncthing-gui-pass.age;
    owner = "bittermang";
    group = "users";
    mode = "0400";
  };

  # WiFi network credentials for iwd
  # Path must match the network SSID exactly: /var/lib/iwd/<SSID>.psk
  # File content format:
  #   [Security]
  #   Passphrase=your-wifi-password
  age.secrets."wifi-home" = {
    file = ./secrets/wifi-home.age;
    path = "/var/lib/iwd/Minus World.psk";
    owner = "root";
    group = "root";
    mode = "0600";
  };
}
